# Generated by Django 5.1.6 on 2026-08-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcosystemThreatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Threat Code')),
                ('name_ar', models.CharField(max_length=255, verbose_name='Name (Arabic)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabic)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
            ],
            options={
                'verbose_name': 'Ecosystem Threat Category',
                'verbose_name_plural': 'Ecosystem Threat Categories',
            },
        ),
        migrations.CreateModel(
            name='SDGGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. SDG6, SDG13', max_length=10, unique=True, verbose_name='SDG Code')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Goal Number')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title (Arabic)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabic)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('color_hex', models.CharField(default='#000000', max_length=7, verbose_name='Hex Color Code')),
                ('icon', models.FileField(blank=True, null=True, upload_to='sdg_icons/', verbose_name='Icon/Logo')),
            ],
            options={
                'verbose_name': 'SDG Goal',
                'verbose_name_plural': 'SDG Goals',
                'ordering': ['number'],
            },
        ),
    ]
