# Generated by Django 5.1.6 on 2026-08-19 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Name (Arabic)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Article Category',
                'verbose_name_plural': 'Article Categories',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title (Arabic)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('summary_ar', models.TextField(blank=True, verbose_name='Summary (Arabic)')),
                ('summary_en', models.TextField(blank=True, verbose_name='Summary (English)')),
                ('file', models.FileField(upload_to='publications/files/', verbose_name='PDF Document')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='publications/covers/', verbose_name='Cover Image')),
                ('published_at', models.DateField(verbose_name='Publication Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Publication / Report',
                'verbose_name_plural': 'Publications / Reports',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=255, verbose_name='Title (Arabic)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('summary_ar', models.TextField(blank=True, verbose_name='Summary (Arabic)')),
                ('summary_en', models.TextField(blank=True, verbose_name='Summary (English)')),
                ('content_ar', models.TextField(verbose_name='Content (Arabic)')),
                ('content_en', models.TextField(verbose_name='Content (English)')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/images/', verbose_name='Featured Image')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.articlecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
