# Generated by Django 6.1 on 2026-08-12 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_administrativeunit_name_ar_and_more'),
        ('observations', '0002_alter_geoobservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoobservation',
            name='status_ar',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending Review'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='geoobservation',
            name='status_en',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending Review'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='geoobservation',
            name='subdomain_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='observations.observationsubdomain', verbose_name='Subdomain'),
        ),
        migrations.AddField(
            model_name='geoobservation',
            name='subdomain_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='observations.observationsubdomain', verbose_name='Subdomain'),
        ),
        migrations.AddField(
            model_name='geoobservation',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='geoobservation',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geoobservation',
            name='admin_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='locations.administrativeunit', verbose_name='Administrative Unit'),
        ),
        migrations.AlterField(
            model_name='geoobservation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending Review'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='geoobservation',
            name='subdomain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='observations.observationsubdomain', verbose_name='Subdomain'),
        ),
    ]
