# Generated by Django 5.1.6 on 2026-08-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Snapshot Date')),
                ('total_observations', models.PositiveIntegerField(default=0, verbose_name='Total Observations')),
                ('verified_observations', models.PositiveIntegerField(default=0, verbose_name='Verified Observations')),
                ('avg_ndvi', models.FloatField(default=0.0, verbose_name='Average NDVI')),
                ('critical_hotspots', models.PositiveIntegerField(default=0, verbose_name='Critical Hotspots Count')),
                ('governorate_breakdown', models.JSONField(default=dict, verbose_name='Governorate Breakdown')),
                ('sdg_distribution', models.JSONField(default=dict, verbose_name='SDG Distribution')),
                ('layer_distribution', models.JSONField(default=dict, verbose_name='Layer Distribution')),
            ],
            options={
                'verbose_name': 'Analytics Snapshot',
                'verbose_name_plural': 'Analytics Snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
