# Generated by Django 6.1 on 2026-08-11 08:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Organization ID')),
                ('name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Organization Name')),
                ('name_ar', models.CharField(max_length=255, null=True, verbose_name='Organization Name')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Organization Code')),
                ('org_type', models.CharField(choices=[('NGO', 'Non-Governmental Organization'), ('GOVERNMENT', 'Government Agency'), ('RESEARCH', 'Research & Academic Institution'), ('FOUNDATION', 'Environmental Foundation'), ('PRIVATE', 'Private Enterprise')], db_index=True, default='NGO', max_length=20, verbose_name='Organization Type')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('description_en', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('description_ar', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, default='', verbose_name='Website')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
    ]
