# Generated by Django 6.1 on 2026-08-10 21:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('level', models.IntegerField(choices=[(1, 'Governorate / Level 1'), (2, 'District / Level 2'), (3, 'Subdistrict / Level 3')], db_index=True, default=1)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.administrativeunit')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
    ]
