# Generated by Django 6.1 on 2026-08-11 08:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeunit',
            name='name_ar',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='administrativeunit',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='administrativeunit',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='administrativeunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='administrativeunit',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Geometry'),
        ),
        migrations.AlterField(
            model_name='administrativeunit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Administrative Unit ID'),
        ),
        migrations.AlterField(
            model_name='administrativeunit',
            name='level',
            field=models.IntegerField(choices=[(1, 'Governorate / Level 1'), (2, 'District / Level 2'), (3, 'Subdistrict / Level 3')], db_index=True, default=1, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='administrativeunit',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='administrativeunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.administrativeunit', verbose_name='Parent Unit'),
        ),
    ]
