# Generated by Django 6.1 on 2026-08-10 21:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationSubdomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(choices=[('WATER', 'Water Resources'), ('AIR', 'Air & Climate'), ('SOIL', 'Soil & Land'), ('ECOLOGY', 'Ecology & Vegetation'), ('URBAN', 'Urban & Waste')], db_index=True, max_length=50)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sdg_alignment', models.CharField(blank=True, help_text='e.g. SDG 6.3.2', max_length=20, null=True)),
                ('metric_template', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['domain', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeoObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('observation_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='locations.administrativeunit')),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='observations.observationsubdomain')),
            ],
            options={
                'ordering': ['-observation_time'],
            },
        ),
        migrations.CreateModel(
            name='MetricReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameter_code', models.CharField(help_text='e.g. pH, NO2, Turbidity', max_length=50)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('text_value', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(max_length=30)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='observations.geoobservation')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('numeric_value__isnull', False), ('text_value__isnull', False), _connector='OR'), name='metric_value_not_both_null')],
            },
        ),
    ]
