# Generated by Django 6.1 on 2026-08-11 08:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geoobservation',
            options={'ordering': ['-observation_time'], 'verbose_name': 'Geo Observation', 'verbose_name_plural': 'Geo Observations'},
        ),
        migrations.AlterModelOptions(
            name='observationsubdomain',
            options={'ordering': ['domain', 'name'], 'verbose_name': 'Observation Subdomain', 'verbose_name_plural': 'Observation Subdomains'},
        ),
        migrations.AlterField(
            model_name='geoobservation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending Review'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='metricreading',
            name='numeric_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Numeric Value'),
        ),
        migrations.AlterField(
            model_name='metricreading',
            name='parameter_code',
            field=models.CharField(help_text='e.g. pH, NO2, Turbidity', max_length=50, verbose_name='Parameter Code'),
        ),
        migrations.AlterField(
            model_name='metricreading',
            name='text_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Text Value'),
        ),
        migrations.AlterField(
            model_name='metricreading',
            name='unit',
            field=models.CharField(max_length=30, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='observationsubdomain',
            name='domain',
            field=models.CharField(choices=[('WATER', 'Water Resources'), ('AIR', 'Air & Climate'), ('SOIL', 'Soil & Land'), ('ECOLOGY', 'Ecology & Vegetation'), ('URBAN', 'Urban & Waste')], max_length=50, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='observationsubdomain',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Subdomain ID'),
        ),
        migrations.AlterField(
            model_name='observationsubdomain',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Subdomain Name'),
        ),
        migrations.AlterField(
            model_name='observationsubdomain',
            name='sdg_alignment',
            field=models.CharField(blank=True, help_text='e.g. SDG 6.3.2', max_length=20, null=True, verbose_name='SDG Alignment'),
        ),
    ]
