# Generated by Django 5.1.6 on 2026-08-13 00:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observations', '0003_geoobservation_status_ar_geoobservation_status_en_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Intervention Title')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='Intervention Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Intervention Title')),
                ('description', models.TextField(verbose_name='Description / Scope of Work')),
                ('description_ar', models.TextField(null=True, verbose_name='Description / Scope of Work')),
                ('description_en', models.TextField(null=True, verbose_name='Description / Scope of Work')),
                ('intervention_type', models.CharField(choices=[('REFORESTATION', 'Reforestation / Vegetation'), ('WATER_TREATMENT', 'Water Quality Restoration'), ('WASTE_CLEANUP', 'Waste & Pollution Removal'), ('HABITAT_PROTECTION', 'Habitat & Wildlife Protection')], max_length=30, verbose_name='Intervention Type')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SUSPENDED', 'Suspended')], default='PLANNED', max_length=20, verbose_name='Status')),
                ('location', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Location / Area Geometry')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='organizations.organization', verbose_name='Responsible Organization')),
                ('target_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='observations.geoobservation', verbose_name='Target Geo Observation')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
            },
        ),
    ]
